# Generated by Django 3.1.12 on 2025-08-13 21:53

import api.models
from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20250813_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='tags',
            field=djongo.models.fields.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='problem',
            name='test_cases',
            field=djongo.models.fields.ArrayField(blank=True, model_container=api.models.TestCase),
        ),
    ]
